name 'HTSlib'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apache2'
description 'Installs/Configures HTSlib'
long_description 'Installs/Configures HTSlib'
source_url 'https://github.com/EagleGenomics-cookbooks/HTSlib'
issues_url 'https://github.com/EagleGenomics-cookbooks/HTSlib/issues'
version '1.0.6'

depends 'apt'
depends 'build-essential'
depends 'magic_shell'
